baseURL = 'https://desistdaydream.github.io/'
# publishDir = "desistdaydream.github.io" # 指定用于构建静态文件后，这些文件的保存目录。默认是 /publish 目录。
title = '断念梦的站点'

# 语言设置
contentDir = "content/zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

enableGitInfo = true

# URL 生成逻辑
disablePathToLower = true # 不要将 URL 路径转为小写
uglyURLs = false          # URL 路径中最后不要带 .html 后缀

# 渲染时忽略的文件
ignoreFiles = ["/content/zh-cn/obsidian_template/.*"]
