[zh-cn]
languageName = "中文"
# 用于权重的排序
weight = 1

[zh-cn.params]
title = "断念梦"
description = "个人站点"

[en]
languageName = "English"
weight = 2
[en.params]
title = "DesistDaydream"
description = "Personal site"
